  name: test1
  on:
    push:
      branches:
         -main
         -'releases/**'
    pull_request:
         branches:
             -main
             -'releases/**'
             
             
                
             

